# Generated by Django 4.2.1 on 2023-05-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_alter_uploadedfile_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='TestFiles/pdf'),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='year_published',
            field=models.IntegerField(),
        ),
    ]
