# Generated by Django 4.2.1 on 2023-05-16 06:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='book_cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='TestFile/cover'),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(upload_to='TestFiles/pdf', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
