# Generated by Django 4.2.1 on 2023-05-24 02:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_customuser_expirytime_customuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='expiryTime',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='token',
            field=models.CharField(blank=True, default='', null=True, unique=True),
        ),
    ]
