# Generated by Django 4.2.1 on 2023-05-24 11:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0012_alter_uploadedfile_book_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='book_cover',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='TestFile/cover', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpeg'])]),
        ),
    ]
